### ISSUE TITLE
Camares Branding Slideshow Colors

### ISSUE THREAD

**Issue by linuxergr** [calamares/calamares-branding#2]
Hi, I would like to know how to set properly the background slideshow color to #2A2A2A and text slideshow color to #97DDFA, in order to apply my transparent slides.

Regards

**Comment by demmm** [comment]
Background color is set in Slide.qml:
https://github.com/calamares/calamares/blob/calamares/src/qml/calamares/slideshow/Slide.qml#L180
You can adjust all those setting in your custom Show.qml, example of setting text color:
https://github.com/calamares/calamares-extensions/blob/calamares/branding/kaos_branding/show.qml#L47

**Comment by adriaandegroot** [comment]
This has been adequately answered here and on IRC (the existing example + Slide is enough, don't need more documentation)
